services:
  postgres:
    container_name: credit_core_postgres
    image: postgres:15
    environment:
      POSTGRES_USER: credit_core
      POSTGRES_PASSWORD: core_pass
      POSTGRES_DB: credit_core
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - microservices-net
    restart: unless-stopped

  redis:
    container_name: credit_core_redis
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - microservices-net
    restart: unless-stopped
    volumes:
      - redis_data:/data
#    command: [ "redis-server", "--loadmodule", "/usr/lib/redis/modules/redisgraph.so" ]

networks:
  microservices-net:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
